import { motion } from "framer-motion";
import { Plus, FileText, ArrowRight, ArrowUpRight, Layers, CheckCircle2, XCircle, MessageSquare, Clock, RefreshCw, AlertCircle, TrendingUp, Send } from "lucide-react";
import { useDashboardData } from "../../hooks/useDashboardData";
import DonutChart from "./DonutChart";
const COLORS = { approved: "#a4b3a0", declined: "#bd6a65", negotiated: "#e8b989", pending: "#681b24" };
const LABELS = { approved: "Approved", declined: "Declined", negotiate: "In negotiation", pending: "Pending" };
const animation = { hidden: { opacity: 0, y: 12 }, show: { opacity: 1, y: 0 } };

function ActivityChart({ series = [] }) {
  const data = series.length ? series : Array.from({ length: 6 }, (_, index) => ({ label: new Date(new Date().getFullYear(), new Date().getMonth() - 5 + index, 1).toLocaleDateString(undefined, { month: "short" }), value: 0 }));
  const maximum = Math.max(...data.map((month) => month.value), 2);
  return <div className="activity-chart" role="img" aria-label={`Quotations by month: ${data.map((month) => `${month.label}: ${month.value}`).join(", ")}`}><div className="activity-grid-lines"><span>{maximum}</span><span>{Math.round(maximum / 2)}</span><span>0</span></div><div className="activity-bars">{data.map((month, index) => <div className="activity-column" key={`${month.label}-${index}`}><div className="activity-bar-track"><div className={`activity-bar ${index === 5 ? "is-current" : ""}`} style={{ height: `${Math.max(month.value / maximum * 100, 2)}%` }}><span>{month.value}</span></div></div><span className="activity-month">{month.label}</span></div>)}</div></div>;
}
export default function Overview({ presets, userName = "there", onCreatePreset, onOpenForm, onManagePresets, onOpenDatabase }) {
  const { state, error, stats, reload } = useDashboardData(presets);
  const busy = state === "loading";
  const approvalRate = stats.total ? Math.round(stats.approved / stats.total * 100) : 0;
  const cards = [
    { key: "approved", label: "Approved", icon: CheckCircle2, note: "Ready to move forward" },
    { key: "pending", label: "Awaiting response", icon: Clock, note: "Your next follow-up" },
    { key: "negotiated", label: "In negotiation", icon: MessageSquare, note: "Keep the conversation going" },
    { key: "declined", label: "Declined", icon: XCircle, note: "Part of the bigger picture" },
  ];
  const segments = Object.keys(COLORS).map((key) => ({ label: key === "negotiated" ? "Negotiation" : LABELS[key], value: stats[key], color: COLORS[key] }));
  return <div className="screen screen-wide dashboard-screen">
    <header className="screen-head"><div><p className="screen-eyebrow">YOUR BUSINESS, AT A GLANCE</p><h1 className="screen-title">Hello, {userName.split(" ")[0]}<span className="greeting-dot">.</span></h1><p className="screen-sub">A clearer view of your quotations. A better start to your day.</p></div><div className="head-actions"><button className="btn btn-soft" onClick={reload} disabled={busy}><RefreshCw size={16} className={busy ? "spin" : ""} />Refresh</button><button className="btn btn-primary" onClick={onCreatePreset}><Plus size={17} />Create a preset</button></div></header>
    {error && <div className={`alert ${state === "error" ? "alert-error" : "alert-info"}`}><AlertCircle size={18} /><span>{state === "error" ? error : `Some preset data could not be loaded: ${error}`}</span></div>}
    <div className="overview-grid"><motion.section className="overview-balance" variants={animation} initial="hidden" animate="show"><div className="balance-heading"><span><FileText size={17} />Quotation workspace</span><span className="balance-pill">Overview</span></div><div className="balance-total">{busy ? "…" : stats.total.toLocaleString()}<span>Total quotations</span></div><div className="balance-footer"><span><span className="balance-dot" />{presets.length} available preset{presets.length === 1 ? "" : "s"}</span><button onClick={() => onOpenDatabase()} aria-label="Browse all quotations"><ArrowUpRight size={22} /></button></div><span className="balance-orbit balance-orbit-one" /><span className="balance-orbit balance-orbit-two" /></motion.section><section className="card activity-card"><div className="panel-heading"><div><h2>Quotation activity</h2><p>Created over the last six months</p></div><span className="panel-icon"><TrendingUp size={19} /></span></div><ActivityChart series={stats.activity} /></section></div>
    <motion.div className="metric-row" initial="hidden" animate="show" transition={{ staggerChildren: 0.05 }}>{cards.map(({ key, label, icon: Icon, note }) => <motion.section className={`stat-card metric-card metric-${key}`} variants={animation} key={key}><div className="metric-top"><span>{label}</span><Icon size={18} /></div><div className="stat-value">{busy ? "…" : stats[key].toLocaleString()}</div><div className="metric-note">{note}</div></motion.section>)}</motion.div>
    <div className="dashboard-detail-grid"><section className="card recent-card"><div className="panel-heading"><div><h2>Recent quotations</h2><p>The latest from your workspace</p></div><button className="btn btn-ghost btn-xs" onClick={() => onOpenDatabase()}>View all <ArrowUpRight size={15} /></button></div>{stats.recent?.length ? <div className="recent-table-wrap"><table className="recent-table"><thead><tr><th>Quotation</th><th>Created</th><th>Status</th><th><span className="sr-only">Open</span></th></tr></thead><tbody>{stats.recent.map((quote, index) => <tr key={`${quote.quotationId}-${index}`}><td><div className="recent-identity"><span className="recent-document"><FileText size={17} /></span><span><strong title={quote.quotationId}>{quote.quotationId || "Quotation"}</strong><small>{quote.presetName}</small></span></div></td><td>{quote.createdAt && !Number.isNaN(new Date(quote.createdAt).getTime()) ? new Date(quote.createdAt).toLocaleDateString(undefined, { month: "short", day: "numeric" }) : "—"}</td><td><span className={`decision-pill decision-${quote.decision}`}>{LABELS[quote.decision] || "Pending"}</span></td><td><button className="icon-btn" onClick={() => onOpenDatabase(quote.presetId)} aria-label={`Open ${quote.quotationId || "quotation"}`}><ArrowUpRight size={16} /></button></td></tr>)}</tbody></table></div> : <div className="workspace-empty"><span className="empty-document"><FileText size={26} /></span><h3>Your next opportunity starts here</h3><p>Create a preset, fill in your details, and save your first quotation.</p><button className="btn btn-soft" onClick={onManagePresets}>Explore presets <ArrowRight size={16} /></button></div>}</section><section className="card status-overview"><div className="panel-heading"><div><h2>Your pipeline</h2><p>Every decision, in perspective</p></div><Send size={18} /></div><div className="pipeline-chart"><DonutChart segments={segments} total={stats.total} /></div><div className="pipeline-rate"><strong>{approvalRate}%</strong><span>approval rate</span></div><div className="pipeline-legend">{segments.map((segment) => <div className="legend-row" key={segment.label}><span className="legend-dot" style={{ background: segment.color }} /><span className="legend-label">{segment.label}</span><span className="legend-value">{segment.value}</span></div>)}</div></section></div>
    <div className="section-head"><div><span className="screen-eyebrow">BUILT AROUND YOUR BUSINESS</span><h2>Your presets</h2></div><button className="btn btn-ghost" onClick={onManagePresets}>Manage presets <ArrowUpRight size={16} /></button></div>{presets.length ? <div className="preset-grid">{presets.map((preset, index) => <motion.button key={preset.id} className="preset-tile" whileHover={{ y: -3 }} onClick={() => onOpenForm(preset.id)}><div className="preset-tile-top"><span className="preset-tile-icon"><Layers size={21} /></span><span className="preset-chip">{String(index + 1).padStart(2, "0")}</span></div><h3>{preset.name}</h3><p>{preset.description || "A reusable layout for your next quotation."}</p><div className="preset-tile-foot"><span>{preset.fields.length} custom fields</span><span className="preset-use">Use preset <ArrowUpRight size={16} /></span></div></motion.button>)}</div> : <div className="empty-state"><Layers size={28} /><p>Design your first quotation preset to get started.</p><button className="btn btn-primary" onClick={onCreatePreset}><Plus size={17} />Create a preset</button></div>}
  </div>;
}
